re-org

diff --git a/src/bash/bash-functions b/src/bash/bash-functions
--- a/src/bash/bash-functions
+++ b/src/bash/bash-functions
@@ -634,89 +634,6 @@ ssh() {
   fi
 }
 
--ssh-proxy-connect() {
-  local otp=$1 connect_dest=$2 pl_file
-  if ! pl_file=$(mktemp); then
-    echo "$FUNCNAME: mktemp failed" >&2
-    return 1
-  fi
-  echo '
-BEGIN {
-  $|=1;
-  unlink $0;
-}
-my ($SCR_PORT,$otp,$connect_dest)=@ARGV;
-
-my $sock1=IO::Socket::INET->new(
-  Proto=>"tcp",
-  Blocking=>1,
-  PeerAddr=>"127.0.0.1",
-  PeerPort=>$SCR_PORT) or die "Cannot create socket - $IO::Socket::errstr\n";
-#$sock1->autoflush(1);
-
-# send request headers
-$sock1->send(sprintf("CONNECT %s HTTP/1.0\r\n",$connect_dest));
-$sock1->send(sprintf("X-Scrash-Otp: %s\r\n",$otp));
-$sock1->send("\r\n");
-
-# read response headers
-chomp(my $status_line=readline($sock1));
-printf STDERR "%s\n",$status_line;
-while (chomp(my $hdr=readline($sock1))) {
-  if ($hdr eq "\r") {
-    last;
-  }
-  #printf STDERR "header:<%s>\n",$hdr;
-}
-
-# connect socket bi-directionally to stdin/stdout
-my $c;
-if (my $pid=fork) {
-  while (1) {
-    my $n=sysread(STDIN,$c,512);
-    if ($n==0) {
-      last;
-    }
-    print $sock1 $c;
-  }
-  kill("TERM",$pid);
-} else {
-  while (1) {
-    my $n=sysread($sock1,$c,512);
-    if ($n==0) {
-      last;
-    }
-    print STDOUT $c;
-  }
-}
-' > $pl_file
-  exec perl -mIO::Socket $pl_file $SCR_PORT $otp $connect_dest
-}
-
--sshtool-localhost-known-hosts() {
-  if [ ! -f "$SCR_SSH_USER_KNOWN_HOSTS" ]; then
-    -ws /scr-ssh-user-known-hosts > "$SCR_SSH_USER_KNOWN_HOSTS"
-  fi
-}
-
--sshtool-localhost() {
-  local sshtool=$1 otp cmd
-  shift
-  if otp=$(-ws-set-otp); then
-    -sshtool-localhost-known-hosts
-    cmd=(
-      $sshtool
-      -oConnectTimeout=10
-      -oUserKnownHostsFile="$SCR_SSH_USER_KNOWN_HOSTS"
-      -oProxyCommand="bash -c -- \"-ssh-proxy-connect $otp $SCR_SSH_HOST:22\""
-      #-oProxyCommand="nc -X connect -x 127.0.0.1:$SCR_PORT localhost-otp-$otp 22"
-    )
-    "${cmd[@]}" "$@"
-  else
-    return 1
-  fi
-}
-
 -ssh-auth-sock() {
   local SSH_AUTH_SOCK umask otp arg i rc pid pl_file
   if [ -z "$SCR_SSH_AUTH_SOCK" ]; then
@@ -816,6 +733,89 @@ if (my $pid=fork) {
     kill $pid
   fi
   return $rc
+}
+
+-ssh-proxy-connect() {
+  local otp=$1 connect_dest=$2 pl_file
+  if ! pl_file=$(mktemp); then
+    echo "$FUNCNAME: mktemp failed" >&2
+    return 1
+  fi
+  echo '
+BEGIN {
+  $|=1;
+  unlink $0;
+}
+my ($SCR_PORT,$otp,$connect_dest)=@ARGV;
+
+my $sock1=IO::Socket::INET->new(
+  Proto=>"tcp",
+  Blocking=>1,
+  PeerAddr=>"127.0.0.1",
+  PeerPort=>$SCR_PORT) or die "Cannot create socket - $IO::Socket::errstr\n";
+#$sock1->autoflush(1);
+
+# send request headers
+$sock1->send(sprintf("CONNECT %s HTTP/1.0\r\n",$connect_dest));
+$sock1->send(sprintf("X-Scrash-Otp: %s\r\n",$otp));
+$sock1->send("\r\n");
+
+# read response headers
+chomp(my $status_line=readline($sock1));
+printf STDERR "%s\n",$status_line;
+while (chomp(my $hdr=readline($sock1))) {
+  if ($hdr eq "\r") {
+    last;
+  }
+  #printf STDERR "header:<%s>\n",$hdr;
+}
+
+# connect socket bi-directionally to stdin/stdout
+my $c;
+if (my $pid=fork) {
+  while (1) {
+    my $n=sysread(STDIN,$c,512);
+    if ($n==0) {
+      last;
+    }
+    print $sock1 $c;
+  }
+  kill("TERM",$pid);
+} else {
+  while (1) {
+    my $n=sysread($sock1,$c,512);
+    if ($n==0) {
+      last;
+    }
+    print STDOUT $c;
+  }
+}
+' > $pl_file
+  exec perl -mIO::Socket $pl_file $SCR_PORT $otp $connect_dest
+}
+
+-sshtool-localhost-known-hosts() {
+  if [ ! -f "$SCR_SSH_USER_KNOWN_HOSTS" ]; then
+    -ws /scr-ssh-user-known-hosts > "$SCR_SSH_USER_KNOWN_HOSTS"
+  fi
+}
+
+-sshtool-localhost() {
+  local sshtool=$1 otp cmd
+  shift
+  if otp=$(-ws-set-otp); then
+    -sshtool-localhost-known-hosts
+    cmd=(
+      $sshtool
+      -oConnectTimeout=10
+      -oUserKnownHostsFile="$SCR_SSH_USER_KNOWN_HOSTS"
+      -oProxyCommand="bash -c -- \"-ssh-proxy-connect $otp $SCR_SSH_HOST:22\""
+      #-oProxyCommand="nc -X connect -x 127.0.0.1:$SCR_PORT localhost-otp-$otp 22"
+    )
+    "${cmd[@]}" "$@"
+  else
+    return 1
+  fi
 }
 
 -upload() {
