1.7.0: revamp password handling

diff --git a/src/bash/bash-functions b/src/bash/bash-functions
--- a/src/bash/bash-functions
+++ b/src/bash/bash-functions
@@ -1114,14 +1114,16 @@ bi_directional_pipe(\*STDIN,\*STDOUT,$socket);
 # limitation: password cannot contain a colon because that is assumed to be the
 # delimiter here
 -pw() {
-  local opt OPTIND search_key pw_line pw n index=-1 split_char=':' b64=0 pw_file="$SCR_PASSWORD_FILE" found=0
-  while builtin getopts "hbi:p:" opt; do
+  local opt OPTIND search_key pw_line pw n index=-1 split_char=':' b64=0 pw_file="$SCR_PASSWORD_FILE" found=0 mode=query
+  while builtin getopts "hbi:p:eI" opt; do
     case $opt in
       (h)
-        echo "usage: $FUNCNAME [-hb][-i index][-p password_file] search_key"
+        echo "usage: $FUNCNAME [-hbeI][-i index][-p password_file] search_key"
         echo "-h: this help"
         echo "-b: base64 encode the result"
+        echo "-e: edit the password file"
         echo "-i: for each matched line, return this index value of the line when it is split by \"$split_char\""
+        echo "-I: check for existence of password file, and initialize it if necessary"
         echo "-p: specify an alternate password file, default=$pw_file"
         return
         ;;
@@ -1133,43 +1135,74 @@ bi_directional_pipe(\*STDIN,\*STDOUT,$socket);
         # default is the last index
         index=$OPTARG
         ;;
+      (I)
+        mode=init
+        ;;
       (p)
         pw_file="$OPTARG"
         ;;
+      (e)
+        mode=edit
+        ;;
     esac
   done
-  shift $(($OPTIND-1))
-  search_key="$1"
-  shift
-  if [ $SCR_SSH_LEVEL = 0 ]; then
-    if [ ! -r "$pw_file" ]; then
-      echo "$FUNCNAME: could not read password file: $pw_file" >&2
-      return 1
-    fi
-    while read -r pw_line; do
-      found=1
-      IFS="$split_char" builtin read -r -a pw_line <<<"$pw_line"
-      if [ "$index" ]; then
-        let n=$index || true
-      else
-        let n=${#pw_line[*]}-1
+  case $mode in
+    (init)
+      if [ $SCR_SSH_LEVEL -gt 0 ]; then
+        echo "cannot do this at SCR_SSH_LEVEL=$SCR_SSH_LEVEL" >&2
+        return 1
       fi
-      pw="${pw_line[$n]}"
-      if [ $b64 = 0 ]; then
-        echo "$pw"
-      else
-        printf "%s\n" $(printf %s "$pw" | openssl enc -a -A)
+      if [ ! -f "$pw_file" ]; then
+        # create a blank password file
+        local tmpfile=$(mktemp)
+        printf "#\n# enter secrets here in this format:\n# <login url or description>:<username>:<password>\n#\n" > $tmpfile
+        gpg -ea -r $SCR_PASSWORD_KEY_ID -o $pw_file $tmpfile
+        rm $tmpfile
+        read -p "just created $pw_file, you should add it to git now"
       fi
-    done < <(gpg -qd "$pw_file" | grep "$search_key")
-    if [ $found = 0 ]; then
-      return 1
-    fi
-  elif -ws -o /scr-get-password --data-urlencode "searchKey=$search_key" --data-urlencode "b64=$b64"  --data-urlencode "index=$index" --data-urlencode "pwFile=$pw_file" "$@"; then
-    :
-  else
-    echo "$FUNCNAME: problem with OTP" >&2
-    return 1
-  fi
+      ;;
+    (edit)
+      if [ $SCR_SSH_LEVEL -gt 0 ]; then
+        echo "cannot do this at SCR_SSH_LEVEL=$SCR_SSH_LEVEL" >&2
+        return 1
+      fi
+      vim "$pw_file"
+      ;;
+    (query)
+      shift $(($OPTIND-1))
+      search_key="$1"
+      shift
+      if [ $SCR_SSH_LEVEL = 0 ]; then
+        if [ ! -r "$pw_file" ]; then
+          echo "$FUNCNAME: could not read password file: $pw_file" >&2
+          return 1
+        fi
+        while read -r pw_line; do
+          found=1
+          IFS="$split_char" builtin read -r -a pw_line <<<"$pw_line"
+          if [ "$index" ]; then
+            let n=$index || true
+          else
+            let n=${#pw_line[*]}-1
+          fi
+          pw="${pw_line[$n]}"
+          if [ $b64 = 0 ]; then
+            echo "$pw"
+          else
+            printf "%s\n" $(printf %s "$pw" | openssl enc -a -A)
+          fi
+        done < <(gpg -qd "$pw_file" | grep "$search_key")
+        if [ $found = 0 ]; then
+          return 1
+        fi
+      elif -ws -o /scr-get-password --data-urlencode "searchKey=$search_key" --data-urlencode "b64=$b64"  --data-urlencode "index=$index" --data-urlencode "pwFile=$pw_file" "$@"; then
+        :
+      else
+        echo "$FUNCNAME: problem with OTP" >&2
+        return 1
+      fi
+      ;;
+  esac
 }
 
 #
@@ -1179,7 +1212,7 @@ bi_directional_pipe(\*STDIN,\*STDOUT,$socket);
 # If stdout is the tty, the output highlights the search string in red
 #
 -psg() (
-  local ps_cmd ps_output search_string os=$(uname) i l m matched x n=0 ATTR_RED='\x1b[1;31m' ATTR_CLEAR='\x1b[0m' opts="wkhep" opt OPTIND wb1 wb2 pid kill_signal kill_clause edit_mode=0 tmpfile only_pids=0
+  local ps_cmd ps_output search_string os=$(uname) i l m matched x n=0 ATTR_RED='\x1b[1;31m' ATTR_CLEAR='\x1b[0m' opts="wkhep" opt OPTIND wb1 wb2 pid kill_signal kill_clause edit_mode=0 tmpfile only_pids=0 yn
   shopt -s nocasematch
   while builtin getopts $opts opt; do
     case $opt in
