revamp -pw function

diff --git a/src/bash/bash-functions b/src/bash/bash-functions
--- a/src/bash/bash-functions
+++ b/src/bash/bash-functions
@@ -1040,7 +1040,7 @@ bi_directional_pipe(\*STDIN,\*STDOUT,$socket);
 }
 
 -sxx-scr-server-known-hosts() {
-  if [ ! -f "$SCR_SSH_USER_KNOWN_HOSTS" ]; then
+  if [ ! -f "$SCR_SSH_USER_KNOWN_HOSTS" -o ! -s "$SCR_SSH_USER_KNOWN_HOSTS" ]; then
     -ws /scr-ssh-user-known-hosts > "$SCR_SSH_USER_KNOWN_HOSTS"
   fi
 }
@@ -1094,24 +1094,57 @@ bi_directional_pipe(\*STDIN,\*STDOUT,$socket);
 # limitation: password cannot contain a colon because that is assumed to be the
 # delimiter here
 -pw() {
-  local opt OPTIND pwkey no_network=0 pw_line pw n
-  while builtin getopts "N" opt; do
+  local opt OPTIND search_key pw_line pw n index=-1 split_char=':' b64=0 pw_file="$SCR_PASSWORD_FILE" found=0
+  while builtin getopts "hbi:p:" opt; do
     case $opt in
-      (N) # handle edge case when server is not running
-        no_network=1
+      (h)
+        echo "usage: $FUNCNAME [-hb][-i index][-p password_file] search_key"
+        echo "-h: this help"
+        echo "-b: base64 encode the result"
+        echo "-i: for each matched line, return this index value of the line when it is split by \"$split_char\""
+        echo "-p: specify an alternate password file, default=$pw_file"
+        return
+        ;;
+      (b)
+        b64=1
+        ;;
+      (i)
+        # for each line found, within that line what part of the line do we want?
+        # default is the last index
+        index=$OPTARG
+        ;;
+      (p)
+        pw_file="$OPTARG"
         ;;
     esac
   done
   shift $(($OPTIND-1))
-  pwkey="$1"
+  search_key="$1"
   shift
-  if [ $no_network = 1 ]; then
-    pw_line=$(gpg -qd "$SCR_PASSWORD_FILE" | grep "$pwkey" | head -1)
-    IFS=: builtin read -r -a pw_line <<<"$pw_line"
-    let n=${#pw_line[*]}
-    pw="${pw_line[$n-1]}"
-    echo "$pw"
-  elif -ws -o /scr-get-password -d "key=$pwkey" "$@"; then
+  if [ $SCR_SSH_LEVEL = 0 ]; then
+    if [ ! -r "$pw_file" ]; then
+      echo "$FUNCNAME: could not read password file: $pw_file" >&2
+      return 1
+    fi
+    while read pw_line; do
+      found=1
+      IFS="$split_char" builtin read -r -a pw_line <<<"$pw_line"
+      if [ "$index" ]; then
+        let n=$index || true
+      else
+        let n=${#pw_line[*]}-1
+      fi
+      pw="${pw_line[$n]}"
+      if [ $b64 = 0 ]; then
+        echo "$pw"
+      else
+        printf "%s\n" $(printf %s "$pw" | openssl enc -a -A)
+      fi
+    done < <(gpg -qd "$pw_file" | grep "$search_key")
+    if [ $found = 0 ]; then
+      return 1
+    fi
+  elif -ws -o /scr-get-password --data-urlencode "searchKey=$search_key" --data-urlencode "b64=$b64"  --data-urlencode "index=$index" --data-urlencode "pwFile=$pw_file" "$@"; then
     :
   else
     echo "$FUNCNAME: problem with OTP" >&2
