refactor upload/download

diff --git a/profile/el13/bashrc b/profile/el13/bashrc
--- a/profile/el13/bashrc
+++ b/profile/el13/bashrc
@@ -28,4 +28,23 @@ c() {
   -copy-to-clipboard "$@"
 }
 export -f v l c
+
+-totp() {
+  local key_idx=${1:-0} otp key_id base32_key
+  local key_ids=(
+    "TOTP Amazon Web Services:lenio@556585969992"
+    "TOTP LincWare OPS"
+    "TOTP lw-401-main-st"
+  )
+  key_id=${key_ids[$key_idx]}
+  if [ -z "$key_id" ]; then
+    echo "$FUNCNAME: could not acquire base32_key using key_idx=$key_idx" >&2
+    return 1
+  fi
+  base32_key=$(-pw "$key_id")
+  otp=$(oathtool --totp -b $base32_key)
+  printf "%s:%s\n" "$key_id" $otp
+  printf $otp | -copy-to-clipboard
+}
+
 echo "******** sourced mybashrc ********" >&2
