enhance -ssh-load-keys

diff --git a/profile/el13/bash-functions-localhost b/profile/el13/bash-functions-localhost
--- a/profile/el13/bash-functions-localhost
+++ b/profile/el13/bash-functions-localhost
@@ -505,10 +505,15 @@ EOF
 -ssh-askpass() {
   # passphrase_question looks like this:
   #   Enter passphrase for /Users/el13/.ssh/lenio-id_rsa: 
-  local passphrase_question="$1" key
+  local state_file="$1" passphrase_question="$2" key
+  echo "$passphrase_question" >/dev/tty
   if [[ "$passphrase_question" =~ (/[-\._/[:alnum:]]+) ]]; then
-    key="${BASH_REMATCH[1]}"
-    -pw $(basename "$key")
+    key=$(basename "${BASH_REMATCH[1]}")
+    if fgrep -q "$key" $state_file; then
+      return 1
+    fi
+    -pw "$key"
+    echo "$key" >> $state_file
   else
     echo "$FUNCNAME: could not parse ssh key from string: $passphrase_question" >&2
     return 1
@@ -516,15 +521,27 @@ EOF
 }
 
 -ssh-load-keys() {
-  local SSH_ASKPASS=$(mktemp) key keys=(
-    $HOME/.ssh/lenio-id_rsa
-    $HOME/.ssh/remoteadmin-shell-id_rsa
-    $HOME/.ssh/el13-20231106_ed25519
-    ) otp
-  printf '#!/usr/bin/env bash\n-ssh-askpass "$@"\n' >$SSH_ASKPASS
+  # state_file will track which passphrases have been asked for, and if asked
+  # more than once for any given key we need to short circuit ssh-add to fail
+  # (and not keep repeatedly invoking $SSH_ASKPASS for the passphrase)
+  local SSH_ASKPASS=$(mktemp) key keys otp i state_file=$(mktemp)
+  IFS=$'\n' read -d '' -a keys <<<"$(-pw -i 1 SSHKEY)" || true
+  if [ ${#keys[*]} -eq 0 ]; then
+    echo "$FUNCNAME: unable to load list of ssh keys" >&2
+    return 1
+  fi
+  for ((i=0;i<${#keys[@]};i++)); do
+    # resolve any tildes in the filename
+    keys[$i]="${keys[$i]/#\~/$HOME}"
+  done
+  printf '#!/usr/bin/env bash\nset -e\n-ssh-askpass %s "$@"\n' $state_file >$SSH_ASKPASS
   chmod +x $SSH_ASKPASS
-  SSH_ASKPASS_REQUIRE=force SSH_ASKPASS=$SSH_ASKPASS ssh-add "${keys[@]}" </dev/null
-  rm -f $SSH_ASKPASS
+  trap "rm -f $SSH_ASKPASS $state_file" RETURN
+  if SSH_ASKPASS_REQUIRE=force SSH_ASKPASS=$SSH_ASKPASS ssh-add "${keys[@]}" </dev/null; then
+    echo SUCCESS
+  else
+    echo FAIL
+  fi
 }
 
 -ld-crypt() {
