add function to load ssh keys

diff --git a/profile/el13/bash-functions-localhost b/profile/el13/bash-functions-localhost
--- a/profile/el13/bash-functions-localhost
+++ b/profile/el13/bash-functions-localhost
@@ -478,3 +478,26 @@
     echo "nat on $wifi_iface from { $vbox_subnet $qemu_subnet } to any -> $wifi_iface"
   } | sudo pfctl -e -f -
 )
+
+-ssh-askpass() {
+  # passphrase_question looks like this:
+  #   Enter passphrase for /Users/el13/.ssh/lenio-id_rsa: 
+  local passphrase_question="$1" key
+  if [[ "$passphrase_question" =~ (/[-\._/[:alnum:]]+) ]]; then
+    key="${BASH_REMATCH[1]}"
+    -pw $(basename "$key")
+  else
+    echo "$FUNCNAME: could not parse ssh key from string: $passphrase_question" >&2
+    return 1
+  fi
+}
+
+-ssh-load-keys() {
+  local SSH_ASKPASS=$(mktemp) key keys=($HOME/.ssh/lenio-id_rsa $HOME/.ssh/remoteadmin-shell-id_rsa)
+  printf '#!/usr/bin/env bash\n-ssh-askpass "$@"\n' >$SSH_ASKPASS
+  chmod +x $SSH_ASKPASS
+  for key in "${keys[@]}"; do
+    SSH_ASKPASS_REQUIRE=force SSH_ASKPASS=$SSH_ASKPASS ssh-add "$key" </dev/null
+  done
+  rm -f $SSH_ASKPASS
+}
